version: "3.8"

services:
  envoy:
    image: docker.io/library/envoy-proxy
    ports:
      - "8080:8080"
      - "9901:9901"
    networks:
      - mynetwork
    depends_on:
      - wealthsnap

  wealthsnap:
    image: docker.io/library/my-wealthsnap
    ports:
      - "50051:50051"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
